# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fYQ6mnN7YBxXH_BAtb7nFuJSSvTd7tjU
"""

def alphabet(x):

  token ='ABCDEFGHIJKLMNOPQRSTUVWXYZ'

  if x in token:
    return True
  else:
    return False

def precedence(y):

  if y=='!':
    return 5

  elif y=='&':
    return 4

  elif y=='|':
    return 3

  elif y=='>':
    return 2

  elif y=='~':
    return 1


def postfix(exp):
  for i in exp:
    if alphabet(i):
      result.append(i)
    elif len(st)==0:
      st.append(i)
    elif precedence(i) > precedence(st[-1]):
      st.append(i)

    elif precedence(i)== precedence(st[-1]):
      return False
      
    else:
      while (len(st)!=0):
        if (precedence(i)< precedence(st[-1])):
          x=st.pop()
          result.append(x)
        else:
          st.append(i)
      st.append(i)

  if len(st) > 0:
    while(len(st)!=0):
      result.append(st.pop())

  return result




def checkwellformed(y):
  x=len(exp)
  if(x==1):
       return True
  elif (x==2):
    if(exp[0] =='!'and (exp[1].isalpha())):
      return False 
    else:
      return True
    
  elif x>2 : 
    if(exp[0]=='&' or exp[0]=='|' or exp[0]=='>' or exp[0]=='~'):
      return True
    elif (exp[0]=='!' and (not exp[1].isalpha())):
      return True
    else :

      for i in range(0,x-1):
        if (exp[i].isalpha() and exp[i+1].isalpha()):
            return True
        elif (exp[i].isalpha() and exp[i+1]=='!'):
            return True
            
        elif (exp[i].isalpha()):
            i=i+1
        elif (exp[i]=='&' or exp[i]=='|' or exp[i]=='>' or exp[i]=='~'):
          if (exp[i-1].isalpha() and exp[i+1].isalpha()):
            i=i+1
          elif (exp[i-1].isalpha() and exp[i+1]=='!'):
            i=i+1
          else : return True
        elif (exp[i]=='!' and exp[i+1].isalpha()):
          i=i+1
        elif (exp[i]=='!' and (not exp[i+1].isalpha())):
          return True
      return False




def bracket(postfixexp):

  st=[]
  

  for i in postfixexp:
    if alphabet(i):
      st.append(i)

    else:
      if i=='!':
        s=[]
        a=st.pop()
        s.append('(')
        s.append('!')
        s.append(a)
        s.append(')')
        st.append("".join(s))

      else:

        b=st.pop()
        a=st.pop()
        s=[]

        s.append('(')
        s.append(a)
        s.append(i)
        s.append(b)
        s.append(')')
        st.append("".join(s))

  r=("".join(st[::-1]))
  return r
  

      

    



st=[]
result=[]

exp = input("Enter your value: ")
check=checkwellformed(exp)


if check:
  print("Not well formed formula")
else:
  w=postfix(exp)
  if w is False:
      print("Not well formed formula")
  else:
      postfixexp=("".join(w))
      #print(postfixexp)
      Answer=bracket(postfixexp)
      print(Answer)